name: Java CI with MongoDB

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: '8.0'

      - name: Wait for MongoDB
        run: |
          echo "Waiting for MongoDB to be ready..."
          sleep 15

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots clean verify
